### ISSUE TITLE
[feature request] add wiegand decoding to proxmark3 client

### ISSUE THREAD

**Issue by thesle3p** [iceman1001/proxmark3#186]
Hi would it be possible to add a wiegand decoder to the proxmark3 client (maybe under analyse) where you could specify bit length and offsets/lenthgs for FC and Card #  and it could return FC and card number from raw wiegand code? Perhaps  have things like cmdlfawid utilize that  to make the process of dealing with  awid credentials with unusual bit lengths easier for example (replace awid with any other card type that occasionally has a non standard bit length).

**Comment by 0xFFFF** [comment]
This question has come up before. Being able to translate this requires a small database consisting of the various Physical Access Control System (PACS) formats.
Throwing a stream of random bits at a decoder would require user input as there will be a number of false positives.
Have you had a look at [Cardinfo](cardinfo.barkweb.com.au)? What do you think of the results produced?

**Comment by thesle3p** [comment]
What's wrong with user input? This android app https://play.google.com/store/apps/details?id=com.muweili.cardformatcalculator&hl=en does what I am talking about very well I just was thinking it would be nice to do so from the proxmark client.

**Comment by iceman1001** [comment]
I did have a wiegand decoder in **lf hid** before,  removed it since it didn't generate the right raw hex.

The easy part is to make a wiegand calc,.   The hard part is to generate the raw hax bytes needed for the clone commands.   All systems has their own quirks/ encoding layers above the wiegand layer.
 and at the last layer,  is what I call the pm3 layer,  which adds the preamble and other stuff.

So people gets confused and thinks its just wiegand with the implemented dedicated systems like  awid, hid, nedap etc etc.    Behind the scens, it is not.

**Comment by iceman1001** [comment]
@thesle3p   if you are good programmer, you can enable the previous wiegand calc in lf hid..  
and move it to [b]analyze wiegand[/b]    the wiegand part works

**Comment by iceman1001** [comment]
I took the wiegand encoder/decoder from offical repo and added it to RRG/Iceman,  since this repo is deprecated.  

ref
https://github.com/RfidResearchGroup/proxmark3

You find the new command
```
pm3->wiegand
```
